name: Create release request

on:
  workflow_call:
    inputs:
      prerelease:
        required: false
        type: string

jobs:
  release-request:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main
      - name: Create bump and changelog
        id: commitizen
        uses: commitizen-tools/commitizen-action@master
        with:
          prerelease: ${{ inputs.prerelease }}
          git_name: ${{ github.actor }}
          git_email: ${{ github.actor }}@users.noreply.github.com
          push: "false"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release-${{ steps.commitizen.outputs.version }}
          delete-branch: true
          title: "bump: version ${{ steps.commitizen.outputs.version }}"
          body: ""
